name: Publish package to GitHub Packages
on:
  push:
    branches: ['release']
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          server-id: github
          server-username: GITHUB_USER_REF
          server-password: GITHUB_TOKEN_REF
      - name: Publish package
        run: mvn -B -Pgithub deploy
        env:
          GITHUB_USER_REF: ${{ secrets.GH_PACKAGE_REPO_USERNAME }}
          GITHUB_TOKEN_REF: ${{ secrets.GH_PACKAGE_REPO_PASSWORD }}
          GITHUB_TOKEN: ${{ secrets.GH_PACKAGE_REPO_PASSWORD }}
